### ISSUE TITLE
Cross system compatible?

### ISSUE THREAD

**Issue by mlava** [cniweb/openhab-syno-spk#1]
Hi there.
I am about to purchase a DS415+.
Will the 1.7 spk install and work correctly, despite being tested on the 214play, 209 and 101j?
https://github.com/cniweb/openhab-syno-spk/releases

Thanks in advance!

**Comment by cniweb** [comment]
Hi Mark

I think so, because openhab is a Java application, if you have an appropriate Java Runtime installed, it should work.

Regards,
Chris

**Comment by mlava** [comment]
Well, when you put it that way ;-)
Thanks, I appreciate it. Last hurdle before the new purchase overcome!

**Comment by cniweb** [comment]
Hi Mark,

i see the DS415+ is with Intel Atom CPU.
My package only works with DS with ARM CPU.

Sorry

Chris

**Comment by litris** [comment]
You can not change to DS415 + I also use one.

Thanks.

**Comment by mlava** [comment]
@cniweb - thanks for letting me know.

@litris - do you have an alternative? I have been looking online trying to find something for ds415+. Cheers!

**Comment by litris** [comment]
No, I mean if there is any way to modify the code to work in the DS415 + 

Sorry translator of English usage.

**Comment by mlava** [comment]
Ah, sorry about that, I misread our post.

I have posted about this at https://community.openhab.org/t/synology-diskstation/1446 and hope there might be some suggestions soon!

**Comment by cniweb** [comment]
The solution would be that one to the effect modifies the code so that the package works with all CPU architectures. Possibly probably missing in the [INFO](https://github.com/cniweb/openhab-syno-spk/blob/master/INFO) file a corresponding entry.
