### ISSUE TITLE
Invalid File Format

### ISSUE THREAD

**Issue by db1mso** [cniweb/openhab-syno-spk#2]
Hello.

On a DS111 i was unable to install OpenHAB-1.7.1-syno-noarch-0.001.spk. In Package Manager on manual Install, i get error "Invalid File Format"

Cheers 
   Olli

**Comment by MadeInChina** [comment]
On DS214play with same issue.
DS214play
CPU INTEL Atom CE5335
CPU clock rate 1.6 GHz
CPU cores 2
Total physical memory 1024 MB
DSM version DSM 5.2-5592 Update 4

**Comment by federic0** [comment]
Same here, with DS413j DSM 5.2-5592 Update 4, any info on this error?

Cheers

**Comment by mastix** [comment]
Same here. :(

**Comment by krzychb** [comment]
I have the same issue
DS414 - DSM 5.2-5592 Update 4
CPU - MARVELL Armada XP MV78230

**Comment by albertovincenzi** [comment]
Same issue
DSM 5.2-5592 Update 2

**Comment by CondormanFr** [comment]
> i get error "Invalid File Format"

I repack the spk file with TAR file compression and rename it to spk back and It get installed but the install process seems missing the main download of openhab ...So not working at the end ...

DS1515+ - DSM5.2-5592 Update 4

**Comment by cniweb** [comment]
HI,

OK, i make a new package file:
https://github.com/cniweb/openhab-syno-spk/releases/download/1.7.1/OpenHAB-1.7.1-syno-noarch-0.001.zip
Can you test it, please?

Thanks,
Chris

**Comment by federic0** [comment]
Installation went fine, haven't tested further yet.
DS413j DSM 5.2-5592 Update 4
MARVELL Kirkwood 88F6282

**Comment by federic0** [comment]
As I said previously the package installs, however, when trying to load openhab's web server I get errors:
When accessing the demo url:
Problem accessing /openhab.app. Reason:
    Sitemap 'demo' could not be found

And when trying the default url:
Sitemap 'default' could not be found

I've copied openhab_default.cfg to openhab.cfg
But still get the error...
I'm new to OpenHab so it might not be related to the package.

Cheers

**Comment by db1mso** [comment]
Please install the openhab demo package first. A Sitemap 'demo' is included there.

Cheers
   Olli

**Comment by db1mso** [comment]
Hello Chris,
the new released Package works fine.
Thanks for your work.

Greets
   Olli

**Comment by CondormanFr** [comment]
It seems that with the 1.8.0 package, there is the same issue (file format...). Is it possible to have the spk in a zip file ? 
Thanks

**Comment by cniweb** [comment]
Hi @CondormanFr,
I add the SPK to a ZIP File. Tray again, please.

**Comment by cniweb** [comment]
I do this (tar -cvf) to package the content (line 6):
https://github.com/cniweb/openhab-syno-spk/blob/master/.travis.yml

**Comment by CondormanFr** [comment]
Thanks.
The new package works.

**Comment by bytedealer** [comment]
Seems last version is corrupted again: OpenHAB-1.8.2-DSM6-RC-syno-noarch-0.001.spk 
I upgraded to the final release and I get also "invalid format".

See also: https://community.openhab.org/t/synology-diskstation/1446/73

**Comment by cniweb** [comment]
I fixed it!
